### 환경 설정
@base = http://localhost:3000
@accessToken = 
@refreshToken = 

### 로그인
POST {{base}}/auth/login
Content-Type: application/json

{
  "email": "admin1@test.com",
  "password": "admin1234"
}

### 토큰 갱신
POST {{base}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
