### 환경 설정
@base = http://localhost:3000

### 차량 목록 조회
GET {{base}}/cars
### 차량 상세 조회  
GET {{base}}/cars/{carId}
### 차량 모델 목록 조회
GET {{base}}/cars/models

### 차량 등록
POST {{base}}/cars
### 차량 데이터 대용량 업로드
POST {{base}}/upload

### 차량 수정
PATCH {{base}}/cars/{carId}

### 차량 삭제
DELETE {{base}}/cars/{carId}